config/routes.rb
Rails.application.routes.draw do
  root "blogs#index"

  devise_for :users

  resources :users do
    resources :blogs
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5, maximum: 30 }
  validates :body, presence: true, length: { minimum: 20, maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @blogs = Blog.where(user_id: current_user.id)
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    if @blog.save
      flash[:success] = "Post created successfully"
      redirect_to root_path
    else
      flash[:error] = @blog.errors.full_messages
      render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = current_user.blogs.find(params[:id])
    if @blog.update(blog_params)
      flash[:success] = "Post updated successfully"
      redirect_to root_path
    else
      flash[:error] = @blog.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.destroy
      flash[:success] = "Post deleted successfully"
    else
      flash[:error] = @blog.errors.full_messages
    end
    redirect_to root_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class="new-blog">
  <% if @blog.errors.any? %>
    <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_for [current_user, @blog], url: user_blog_path, html: { class: "col s12" } do |b| %>
    <div class="row">
      <div class="input-field col s6">
        <%= b.text_field :title , value: @blog.title, id: "blog-title", type: "text", class: "validate" %>
      </div>
      <div class="input-field col s12">
        <%= b.text_area :body, id: "icon_prefix2", class: "materialize-textarea", value: @blog.body %>
        <label for="icon_prefix2"></label>
      </div>
    </div>
    <%= b.submit "Update", class: "waves-effect waves-light btn-small" %>
  <% end %>
</div>

app/views/blogs/index.html.erb
<div class="row">
  <% @blogs.each do |blog| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= blog.title %></span>
          <p><%= blog.body %></p>
        </div>
        <div class="card-action">
          <a href=<%= edit_user_blog_path(current_user.id, blog.id) %> >Edit</a>
          <%= link_to 'Delete',  user_blog_path(current_user.id, blog.id),  method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class="new-blog">
  <% if @blog.errors.any? %>
    <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_for @blog, url: user_blogs_path, html: { class: "col s12" } do |b| %>
    <div class="row">
      <div class="input-field col s6">
        <%= b.text_field :title , placeholder: "Enter title", id: "blog-title", type: "text", class: "validate" %>
      </div>
      <div class="input-field col s12">
        <%= b.text_area :body, id: "icon_prefix2", class: "materialize-textarea", placeholder: "Fire your idea!" %>
        <label for="icon_prefix2"></label>
      </div>
    </div>
    <%= b.submit "Post", class: "waves-effect waves-light btn-small" %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
    © 2020 Copyright <em>Ganesh Suresh Bhat</em>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <a href=<%= root_path %> class="brand-logo right">R-BLOG</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'New Blog', new_user_blog_path(current_user) %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </div>
    <ul class="sidenav" id="mobile-demo">
      <% if user_signed_in? %>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'New Blog', new_user_blog_path(current_user) %></li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        </ul>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R-BLOG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navigation" %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>